### ISSUE TITLE
Can I use xmlstream to connect to soap webservices?

### ISSUE THREAD

**Issue by NTMS2017** [jorishermans/xmlstream#10]
Hi,

this is the closes plugin I ever see for dart or flutter. I wonder is it possible to use this plugin to connect to soap web services?

thanks

**Comment by jorishermans** [comment]
Don't know, I never tried it out, I guess so, this plugin is created for fast xml parsing. So on top of that you can write a library to parse soap webservice messages.

**Comment by NTMS2017** [comment]
thanks
