### ISSUE TITLE
The space between two tags is eaten

### ISSUE THREAD

**Issue by andyduke** [jorishermans/xmlstream#12]
If there is a space between two tags, it is eaten.
Xml: `<b>bold</b> <i>italic</i>`
Result: **bold**_italic_
Expected: **bold** _italic_

I think that the problem is in this place, unnecessary `trim()`
https://github.com/jorishermans/xmlstream/blob/210340fae5d1bad4ceb5cb7039f5ab1e75d04970/lib/xml/xml_streamer.dart#L80

**Comment by jorishermans** [comment]
I will take a look into this. I need to think of some test to cover this case. Thanks for reporting and using my packages, sorry that it took so long to take this up.

**Comment by jorishermans** [comment]
I made a PR with unit test in it.

**Comment by jorishermans** [comment]
@andyduke I published the xmlstream package to pub. You can use version 0.12.0 now!

**Comment by andyduke** [comment]
> 
> 
> @andyduke I published the xmlstream package to pub. You can use version 0.12.0 now!

Great! Thank you
