### ISSUE TITLE
async and streams

### ISSUE THREAD

**Issue by nocquidant** [jorishermans/xmlstream#7]
Hello,

Thanks you for your great lib.

I build a command line application which merge several xml files and aggregate some stats (sums...).
The streams cause me trouble... As i understand, my command line app could terminate before the streams have been processed and there is no way to wait for the streams to finish.

Thus, according to me, the only option is to handle a RandomAccessFile got with openSync in XmlStreamer...

Could you please confirm?
Thanks 
Nicolas

**Comment by jorishermans** [comment]
Hi,

You can use openRead() as well, look at this example https://github.com/jorishermans/xmlstream/blob/xmlstream/test/hierarchical_test.dart and then the last test, it uses a stream. 

var stream = new File("./test1.xml").openRead(); 
var xmlStreamer = new XmlStreamer.fromStream(stream);

You can also use Future.wait, you can find the info here, this is a helper method that makes it possible to execute futures in an order and with until they are all done. You can find info about future.wait here https://www.dartlang.org/docs/tutorials/futures/.

XmlStreamer works with events. You can use the future that is been returned by the read() method. Every future has a onDone part.

Hopefully this info is usefull for you!

Kind regards,
Joris Hermans

**Comment by nocquidant** [comment]
Yes, thanks!

**Comment by jorishermans** [comment]
Answer is sufficient I suppose!
